## **1. Abstract**

**"How are social media use patterns associated with mental health, sleep quality, and productivity among young adults?"**

## **1.1 Group Members**

1. Jose Paulo Honrado
2. King Mejia
3. Mikael Paule
4. Heart rodrigo
5. Kenji Yasuda

## **2. Dataset Description**

### **2.1 Dataset Selection**

The study will primarily use the *smmh.csv* from the Kaggle dataset *Social Media and Mental Health* because it contains variables that is directly related to social media use, mental health, sleep quality, and productivity-related bahviors. There are also two additional datasets, *Mental_Health_and_Social_Media_Balance_Dataset.csv* and *Social Media Impact on Daily Lives.csv*, will be treated as supporting datasets. These datasets may be used for comparison, but will not be merged into one dataset because each dataset varies from sources, respondents, and variables.

### **2.2 Primary Dataset: smmh.csv**

| Item | Description |
|---|---|
| Source | Kaggle: *Social Media and Mental Health* |
| File used | `smmh.csv` |
| Observations | 481 survey respondents |
| Variables | 21 columns |
| Unit of observation | Each row represents one respondent's response |
| General topic | Social media habits and *self-reported* mental health, sleep, and attention-related experiences |

The dataset contains survey responses about the respondents' demographic, amount of time spent on social media, platform preferences, and self-reported behaviors. Specifically including, using social media without a purpose, distraction, restlessness, worriness, concentration, comparison with others, validation-seeking, feeling depressed, fluctuation on everyday activities, and sleep issues.

The dataset was collected through a survey for a university statistics course project, which focused on different aspects of mental health and how a participant feels any effect on social media use. However, the Kaggle description of the dataset did not specify whether the respondents were randomly selected, how the survey was given, or if the survey was done online or offline. This makes the sampling method unclear and may not fully represent a broad population of young adults. Therefore, the findings from this dataset should be interpreted within the surveyed respondents from the dataset and not towards the population of all young adults.

Since the sampling method was not specified, there is a possibility of having a sampling bias. The dataset may be affected by voluntary response bias or convenience bias. However, it is hard to conclude if there was a bias in this dataset and should be treated as possible limitations because the source of the dataset does not provide enough information about the sampling processes of this dataset.

### **2.3 Attributes of the Primary Dataset**

| Attribute | Columns/Variables | Description |
|---|---|---|
| Response Metadata | Timestamp | Date and time when the survery response was submitted. |
| Demographics | Age, gender, relationship status, occupation status, organization affiliation | Describes the respondent's background and identifies the target group of young adults |
| Social Media access and platforms | Social media use, commonly used platforms | Identifies whether the respondent uses social media and which platforms they use. |
| Social media usage intensity | Average daily time spent on social media | Describes the main variable for comparing heavier-usage and lighter-usage users. |
| Social media behavior patterns | Purposeless use, distracted while bust, restlessness after not using social media | Measures the possible compulsive or disruptive social media behaviors. |
| Productivity-related indicators | Ease of distraction, difficulty concentrating | Used as indicators of productivity or focus difficulties. |
| Mental health indicators | Worry, comparison with others, feelings about comparison, validation-seeking, feeling depressed, fluctuation of interest in daily activities | Used to explore mental health-related patterns associated with social media use. |
| Sleep indicator | Frequency of sleep issues | Used to check the relationship between social media use and sleep-related problems. |

### **2.4 Supporting Datasets**

| Dataset | Source | Observations | Variables | Possible Use-Case |
|---|---|---|---|---|
| Mental_Health_and_Social_Media_Balance_Dataset.csv | Kaggle: Mental Health & Social Media Balance Dataset | 500 | 10 | A supporting dataset that can be used to compare screen time, sleep quality, stress, happiness, exercise, and days without social media. |
| Social Media Impact on Daily Lives.csv | Mendeley Data: The Impact of Social Media on Daily Lives | 522 | 16 | A supporting dataset that can be used to compare daily social media use, addiction, time management, profession, and family time. |

### **2.5 Limitations**

The datasets could be useful for exploring correlations between social media and the well-being of someone, but this comes with limitations. Firstly, the datasets come from different sources, their rows do not represent the same respondents and their columns are not exactly the same either making it difficult to merge the datasets. Second, a lot of these variables are subjective, which may have some bias towards the data. Finally, there is a huge difference in population, survey design, and measurement scales, which could affect how well the comparison of datasets will be.

## **3.0 Data Cleaning & Preprocessing**

### **3.1 Imports and Setup**

In [12]:
print("kernel is working")

kernel is working

In [13]:
import pandas as pd
import numpy as np

df1_raw = pd.read_csv("../data/raw/smmh.csv")
df2_raw = pd.read_csv("../data/raw/Mental_Health_and_Social_Media_Balance_Dataset.csv")
df3_raw = pd.read_csv("../data/raw/Social_Media_Impact_on_Daily_Lives.csv")

In [14]:
df1_clean = df1_raw.copy()

df1_clean = df1_clean.drop(columns = ['Timestamp',
                      '5. What type of organizations are you affiliated with?',
                      '3. Relationship Status'])

df1_clean = df1_clean.rename(columns={
    '1. What is your age?': 'age',
    '2. Gender': 'gender',
    '4. Occupation Status': 'occupation_status',
    '6. Do you use social media?': 'uses_social_media',
    '7. What social media platforms do you commonly use?': 'platforms_used',
    '8. What is the average time you spend on social media every day?': 'daily_time_spent',
    '9. How often do you find yourself using Social media without a specific purpose?': 'purposeless_usage',
    '10. How often do you get distracted by Social media when you are busy doing something?': 'distraction_frequency',
    '11. Do you feel restless if you haven\'t used Social media in a while?': 'restlessness_score',
    '12. On a scale of 1 to 5, how easily distracted are you?': 'distraction_scale',
    '13. On a scale of 1 to 5, how much are you bothered by worries?': 'worry_scale',
    '14. Do you find it difficult to concentrate on things?': 'concentration_difficulty',
    '15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?': 'social_comparison_frequency',
    '16. Following the previous question, how do you feel about these comparisons, generally speaking?': 'comparison_sentiment',
    '17. How often do you look to seek validation from features of social media?': 'validation_seeking',
    '18. How often do you feel depressed or down?': 'depression_scale',
    '19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?': 'interest_fluctuation',
    '20. On a scale of 1 to 5, how often do you face issues regarding sleep?': 'sleep_issue_scale'
})

df1_clean

,age,gender,occupation_status,uses_social_media,platforms_used,daily_time_spent,purposeless_usage,distraction_frequency,restlessness_score,distraction_scale,worry_scale,concentration_difficulty,social_comparison_frequency,comparison_sentiment,validation_seeking,depression_scale,interest_fluctuation,sleep_issue_scale
0,21.0,Male,University Student,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,3,2,5,2,5,2,3,2,5,4,5
1,21.0,Female,University Student,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,3,2,4,5,4,5,1,1,5,4,5
2,21.0,Female,University Student,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,2,1,2,5,4,3,3,1,4,2,5
3,21.0,Female,University Student,Yes,"Facebook, Instagram",More than 5 hours,4,2,1,3,5,3,5,1,2,4,3,2
4,21.0,Female,University Student,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,5,4,4,5,5,3,3,3,4,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,24.0,Male,Salaried Worker,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,4,3,4,3,4,4,2,4,3,4,4
477,26.0,Female,Salaried Worker,Yes,"Facebook, YouTube",Between 1 and 2 hours,2,1,2,3,4,4,4,2,4,4,4,1
478,29.0,Female,Salaried Worker,Yes,"Facebook, YouTube",Between 2 and 3 hours,3,3,4,3,2,3,3,3,4,2,2,2
479,21.0,Male,University Student,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,2,3,2,3,3,2,2,3,4,4,5,4
480,53.0,Male,Salaried Worker,Yes,"Facebook, YouTube",Less than an Hour,2,3,1,3,1,1,3,3,2,2,2,3

In [15]:
# Remove rows where respondent answered "no" in 'uses_social_media' column.
df1_clean = df1_clean[df1_clean["uses_social_media"].str.strip().str.lower() == "yes"].copy()

df1_clean["uses_social_media"].value_counts(dropna=False)

uses_social_media
Yes    478
Name: count, dtype: int64

In [ ]:
# Drop column since we now filtered out all non-social media users
df1_clean = df1_clean.drop(columns=["uses_social_media"])

df1_clean

,age,gender,occupation_status,platforms_used,daily_time_spent,purposeless_usage,distraction_frequency,restlessness_score,distraction_scale,worry_scale,concentration_difficulty,social_comparison_frequency,comparison_sentiment,validation_seeking,depression_scale,interest_fluctuation,sleep_issue_scale
0,21.0,Male,University Student,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,3,2,5,2,5,2,3,2,5,4,5
1,21.0,Female,University Student,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,3,2,4,5,4,5,1,1,5,4,5
2,21.0,Female,University Student,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,2,1,2,5,4,3,3,1,4,2,5
3,21.0,Female,University Student,"Facebook, Instagram",More than 5 hours,4,2,1,3,5,3,5,1,2,4,3,2
4,21.0,Female,University Student,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,5,4,4,5,5,3,3,3,4,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,24.0,Male,Salaried Worker,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,4,3,4,3,4,4,2,4,3,4,4
477,26.0,Female,Salaried Worker,"Facebook, YouTube",Between 1 and 2 hours,2,1,2,3,4,4,4,2,4,4,4,1
478,29.0,Female,Salaried Worker,"Facebook, YouTube",Between 2 and 3 hours,3,3,4,3,2,3,3,3,4,2,2,2
479,21.0,Male,University Student,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,2,3,2,3,3,2,2,3,4,4,5,4
480,53.0,Male,Salaried Worker,"Facebook, YouTube",Less than an Hour,2,3,1,3,1,1,3,3,2,2,2,3

## **Research Question & Exploratory Data Analysis**

## **Summary, Conclusions, and Recommendations**

## **References & Disclosures**