## **1. Abstract**

**"How are social media use patterns associated with mental health, sleep quality, and productivity among young adults?"**

## **1.1 Group Members**

1. Jose Paulo Honrado
2. King Mejia
3. Mikael Paule
4. Heart rodrigo
5. Kenji Yasuda

## **2. Dataset Description**

### **2.1 Dataset Selection**

The study will primarily use the *smmh.csv* from the Kaggle dataset *Social Media and Mental Health* because it contains variables that is directly related to social media use, mental health, sleep quality, and productivity-related bahviors. There are also two additional datasets, *Mental_Health_and_Social_Media_Balance_Dataset.csv* and *Social Media Impact on Daily Lives.csv*, will be treated as supporting datasets. These datasets may be used for comparison, but will not be merged into one dataset because each dataset varies from sources, respondents, and variables.

### **2.2 Primary Dataset: smmh.csv**

| Item | Description |
|---|---|
| Source | Kaggle: *Social Media and Mental Health* |
| File used | `smmh.csv` |
| Observations | 481 survey respondents |
| Variables | 21 columns |
| Unit of observation | Each row represents one respondent's response |
| General topic | Social media habits and *self-reported* mental health, sleep, and attention-related experiences |

The dataset contains survey responses about the respondents' demographic, amount of time spent on social media, platform preferences, and self-reported behaviors. Specifically including, using social media without a purpose, distraction, restlessness, worriness, concentration, comparison with others, validation-seeking, feeling depressed, fluctuation on everyday activities, and sleep issues.

The dataset was collected through a survey for a university statistics course project, which focused on different aspects of mental health and how a participant feels any effect on social media use. However, the Kaggle description of the dataset did not specify whether the respondents were randomly selected, how the survey was given, or if the survey was done online or offline. This makes the sampling method unclear and may not fully represent a broad population of young adults. Therefore, the findings from this dataset should be interpreted within the surveyed respondents from the dataset and not towards the population of all young adults.

Since the sampling method was not specified, there is a possibility of having a sampling bias. The dataset may be affected by voluntary response bias or convenience bias. However, it is hard to conclude if there was a bias in this dataset and should be treated as possible limitations because the source of the dataset does not provide enough information about the sampling processes of this dataset.

### **2.3 Attributes of the Primary Dataset**

| Attribute | Columns/Variables | Description |
|---|---|---|
| Response Metadata | Timestamp | Date and time when the survery response was submitted. |
| Demographics | Age, gender, relationship status, occupation status, organization affiliation | Describes the respondent's background and identifies the target group of young adults |
| Social Media access and platforms | Social media use, commonly used platforms | Identifies whether the respondent uses social media and which platforms they use. |
| Social media usage intensity | Average daily time spent on social media | Describes the main variable for comparing heavier-usage and lighter-usage users. |
| Social media behavior patterns | Purposeless use, distracted while bust, restlessness after not using social media | Measures the possible compulsive or disruptive social media behaviors. |
| Productivity-related indicators | Ease of distraction, difficulty concentrating | Used as indicators of productivity or focus difficulties. |
| Mental health indicators | Worry, comparison with others, feelings about comparison, validation-seeking, feeling depressed, fluctuation of interest in daily activities | Used to explore mental health-related patterns associated with social media use. |
| Sleep indicator | Frequency of sleep issues | Used to check the relationship between social media use and sleep-related problems. |

### **2.4 Supporting Datasets**

| Dataset | Source | Observations | Variables | Possible Use-Case |
|---|---|---|---|---|
| Mental_Health_and_Social_Media_Balance_Dataset.csv | Kaggle: Mental Health & Social Media Balance Dataset | 500 | 10 | A supporting dataset that can be used to compare screen time, sleep quality, stress, happiness, exercise, and days without social media. |
| Social Media Impact on Daily Lives.csv | Mendeley Data: The Impact of Social Media on Daily Lives | 522 | 16 | A supporting dataset that can be used to compare daily social media use, addiction, time management, profession, and family time. |

### **2.5 Limitations**

The datasets could be useful for exploring correlations between social media and the well-being of someone, but this comes with limitations. Firstly, the datasets come from different sources, their rows do not represent the same respondents and their columns are not exactly the same either making it difficult to merge the datasets. Second, a lot of these variables are subjective, which may have some bias towards the data. Finally, there is a huge difference in population, survey design, and measurement scales, which could affect how well the comparison of datasets will be.

## **3.0 Data Cleaning & Preprocessing**

### **3.1 Imports and Setup**

In [12]:
print("kernel is working")

kernel is working

In [30]:
import pandas as pd
import numpy as np

df1_raw = pd.read_csv("../data/raw/smmh.csv")
df2_raw = pd.read_csv("../data/raw/Mental_Health_and_Social_Media_Balance_Dataset.csv")
df3_raw = pd.read_csv("../data/raw/Social_Media_Impact_on_Daily_Lives.csv")

# DF1 cleaning, renaming, and dropping

In [32]:
df1_clean = df1_raw.copy()

df1_clean = df1_clean.drop(columns = ['Timestamp',
                      '5. What type of organizations are you affiliated with?',
                      '3. Relationship Status'])

df1_clean = df1_clean.rename(columns={
    '1. What is your age?': 'age',
    '2. Gender': 'gender',
    '4. Occupation Status': 'occupation_status',
    '6. Do you use social media?': 'uses_social_media',
    '7. What social media platforms do you commonly use?': 'platforms_used',
    '8. What is the average time you spend on social media every day?': 'daily_time_spent',
    '9. How often do you find yourself using Social media without a specific purpose?': 'purposeless_usage',
    '10. How often do you get distracted by Social media when you are busy doing something?': 'distraction_frequency',
    '11. Do you feel restless if you haven\'t used Social media in a while?': 'restlessness_score',
    '12. On a scale of 1 to 5, how easily distracted are you?': 'distraction_scale',
    '13. On a scale of 1 to 5, how much are you bothered by worries?': 'worry_scale',
    '14. Do you find it difficult to concentrate on things?': 'concentration_difficulty',
    '15. On a scale of 1-5, how often do you compare yourself to other successful people through the use of social media?': 'social_comparison_frequency',
    '16. Following the previous question, how do you feel about these comparisons, generally speaking?': 'comparison_sentiment',
    '17. How often do you look to seek validation from features of social media?': 'validation_seeking',
    '18. How often do you feel depressed or down?': 'depression_scale',
    '19. On a scale of 1 to 5, how frequently does your interest in daily activities fluctuate?': 'interest_fluctuation',
    '20. On a scale of 1 to 5, how often do you face issues regarding sleep?': 'sleep_issue_scale'
})

df1_clean

,age,gender,occupation_status,uses_social_media,platforms_used,daily_time_spent,purposeless_usage,distraction_frequency,restlessness_score,distraction_scale,worry_scale,concentration_difficulty,social_comparison_frequency,comparison_sentiment,validation_seeking,depression_scale,interest_fluctuation,sleep_issue_scale
0,21.0,Male,University Student,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,3,2,5,2,5,2,3,2,5,4,5
1,21.0,Female,University Student,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,3,2,4,5,4,5,1,1,5,4,5
2,21.0,Female,University Student,Yes,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,2,1,2,5,4,3,3,1,4,2,5
3,21.0,Female,University Student,Yes,"Facebook, Instagram",More than 5 hours,4,2,1,3,5,3,5,1,2,4,3,2
4,21.0,Female,University Student,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,5,4,4,5,5,3,3,3,4,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,24.0,Male,Salaried Worker,Yes,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,4,3,4,3,4,4,2,4,3,4,4
477,26.0,Female,Salaried Worker,Yes,"Facebook, YouTube",Between 1 and 2 hours,2,1,2,3,4,4,4,2,4,4,4,1
478,29.0,Female,Salaried Worker,Yes,"Facebook, YouTube",Between 2 and 3 hours,3,3,4,3,2,3,3,3,4,2,2,2
479,21.0,Male,University Student,Yes,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,2,3,2,3,3,2,2,3,4,4,5,4
480,53.0,Male,Salaried Worker,Yes,"Facebook, YouTube",Less than an Hour,2,3,1,3,1,1,3,3,2,2,2,3

In [33]:
# Remove rows where respondent answered "no" in 'uses_social_media' column.
df1_clean = df1_clean[df1_clean["uses_social_media"].str.strip().str.lower() == "yes"].copy()

df1_clean["uses_social_media"].value_counts(dropna=False)

uses_social_media
Yes    478
Name: count, dtype: int64

In [34]:
# Drop column since we now filtered out all non-social media users
df1_clean = df1_clean.drop(columns=["uses_social_media"])

df1_clean

,age,gender,occupation_status,platforms_used,daily_time_spent,purposeless_usage,distraction_frequency,restlessness_score,distraction_scale,worry_scale,concentration_difficulty,social_comparison_frequency,comparison_sentiment,validation_seeking,depression_scale,interest_fluctuation,sleep_issue_scale
0,21.0,Male,University Student,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,3,2,5,2,5,2,3,2,5,4,5
1,21.0,Female,University Student,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,3,2,4,5,4,5,1,1,5,4,5
2,21.0,Female,University Student,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,2,1,2,5,4,3,3,1,4,2,5
3,21.0,Female,University Student,"Facebook, Instagram",More than 5 hours,4,2,1,3,5,3,5,1,2,4,3,2
4,21.0,Female,University Student,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,5,4,4,5,5,3,3,3,4,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,24.0,Male,Salaried Worker,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,4,3,4,3,4,4,2,4,3,4,4
477,26.0,Female,Salaried Worker,"Facebook, YouTube",Between 1 and 2 hours,2,1,2,3,4,4,4,2,4,4,4,1
478,29.0,Female,Salaried Worker,"Facebook, YouTube",Between 2 and 3 hours,3,3,4,3,2,3,3,3,4,2,2,2
479,21.0,Male,University Student,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,2,3,2,3,3,2,2,3,4,4,5,4
480,53.0,Male,Salaried Worker,"Facebook, YouTube",Less than an Hour,2,3,1,3,1,1,3,3,2,2,2,3

In [35]:
# Filter age range of DF1 (18-30)
df1_clean["age"] = pd.to_numeric(df1_clean["age"], errors="coerce")

df1_clean = df1_clean[(df1_clean["age"] >= 18) & (df1_clean["age"] <= 30)].copy()

df1_clean

,age,gender,occupation_status,platforms_used,daily_time_spent,purposeless_usage,distraction_frequency,restlessness_score,distraction_scale,worry_scale,concentration_difficulty,social_comparison_frequency,comparison_sentiment,validation_seeking,depression_scale,interest_fluctuation,sleep_issue_scale
0,21.0,Male,University Student,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,5,3,2,5,2,5,2,3,2,5,4,5
1,21.0,Female,University Student,"Facebook, Twitter, Instagram, YouTube, Discord...",More than 5 hours,4,3,2,4,5,4,5,1,1,5,4,5
2,21.0,Female,University Student,"Facebook, Instagram, YouTube, Pinterest",Between 3 and 4 hours,3,2,1,2,5,4,3,3,1,4,2,5
3,21.0,Female,University Student,"Facebook, Instagram",More than 5 hours,4,2,1,3,5,3,5,1,2,4,3,2
4,21.0,Female,University Student,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,5,4,4,5,5,3,3,3,4,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,30.0,Female,Salaried Worker,"Facebook, Instagram, YouTube",Between 4 and 5 hours,2,4,4,3,4,5,4,2,2,4,2,1
476,24.0,Male,Salaried Worker,"Facebook, Instagram, YouTube",Between 2 and 3 hours,3,4,3,4,3,4,4,2,4,3,4,4
477,26.0,Female,Salaried Worker,"Facebook, YouTube",Between 1 and 2 hours,2,1,2,3,4,4,4,2,4,4,4,1
478,29.0,Female,Salaried Worker,"Facebook, YouTube",Between 2 and 3 hours,3,3,4,3,2,3,3,3,4,2,2,2
479,21.0,Male,University Student,"Facebook, Twitter, Instagram, YouTube, Discord...",Between 2 and 3 hours,2,3,2,3,3,2,2,3,4,4,5,4

# DF2 cleaning, renaming, and dropping

In [36]:
df2_clean = df2_raw.copy()

df2_clean = df2_clean.drop(columns=["User_ID"])

df2_clean = df2_clean.rename(columns={
    "Age": "age",
    "Gender": "gender",
    "Daily_Screen_Time(hrs)": "daily_screen_time_hours",
    "Sleep_Quality(1-10)": "sleep_quality",
    "Stress_Level(1-10)": "stress_level",
    "Days_Without_Social_Media": "days_without_social_media",
    "Exercise_Frequency(week)": "exercise_frequency_week",
    "Social_Media_Platform": "primary_social_media_platform",
    "Happiness_Index(1-10)": "happiness_index"
})

df2_clean

,age,gender,daily_screen_time_hours,sleep_quality,stress_level,days_without_social_media,exercise_frequency_week,primary_social_media_platform,happiness_index
0,44,Male,3.1,7.0,6.0,2.0,5.0,Facebook,10.0
1,30,Other,5.1,7.0,8.0,5.0,3.0,LinkedIn,10.0
2,23,Other,7.4,6.0,7.0,1.0,3.0,YouTube,6.0
3,36,Female,5.7,7.0,8.0,1.0,1.0,TikTok,8.0
4,34,Female,7.0,4.0,7.0,5.0,1.0,X (Twitter),8.0
...,...,...,...,...,...,...,...,...,...
495,23,Male,6.9,5.0,7.0,4.0,2.0,X (Twitter),10.0
496,43,Female,5.6,7.0,6.0,5.0,2.0,Facebook,9.0
497,41,Male,7.7,5.0,7.0,2.0,2.0,LinkedIn,8.0
498,23,Male,4.2,9.0,7.0,0.0,2.0,Facebook,9.0
499,43,Female,5.9,5.0,8.0,3.0,3.0,X (Twitter),7.0

In [ ]:
# Set age range
df2_clean["age"] = pd.to_numeric(df2_clean["age"], errors="coerce")

df2_clean = df2_clean[(df2_clean["age"] >= 18) & (df2_clean["age"] <= 30)].copy()

df2_clean

,age,gender,daily_screen_time_hours,sleep_quality,stress_level,days_without_social_media,exercise_frequency_week,primary_social_media_platform,happiness_index
1,30,Other,5.1,7.0,8.0,5.0,3.0,LinkedIn,10.0
2,23,Other,7.4,6.0,7.0,1.0,3.0,YouTube,6.0
6,26,Female,7.8,4.0,8.0,2.0,0.0,TikTok,7.0
7,26,Female,7.4,5.0,6.0,1.0,4.0,Instagram,7.0
10,18,Female,2.8,7.0,6.0,2.0,0.0,Instagram,7.0
...,...,...,...,...,...,...,...,...,...
488,25,Female,8.4,5.0,9.0,1.0,3.0,Facebook,7.0
491,23,Male,3.3,10.0,4.0,2.0,1.0,YouTube,10.0
492,27,Female,4.5,5.0,7.0,6.0,5.0,Facebook,9.0
495,23,Male,6.9,5.0,7.0,4.0,2.0,X (Twitter),10.0
498,23,Male,4.2,9.0,7.0,0.0,2.0,Facebook,9.0

# DF3 cleaning, dropping, and renaming

In [38]:
df3_clean = df3_raw.copy()

df3_clean = df3_clean.drop(columns=["Unnamed: 0",
                                    "Enter your name",
                                    "Do you think privacy policies are effective in social networking sites?",
                                    "Does social media advertising influence the purchase of your product?"])

df3_clean = df3_clean.rename(columns={
    'Enter your age (Ex: 20)': 'age',
    'What is your gender': 'gender',
    'What is your profession?': 'occupation',
    'On an average how many hours a day you spend on your profession?': 'daily_occupation_hours',
    'What social networking sites do you use?': 'social_media_platforms',
    'On an average how many hours a day do you spend on these sites?': 'daily_social_media_hours',
    'On an average how many hours a day do you spend with your family?': 'daily_family_hours',
    'Why do you use these social networking sites?': 'social_media_use_reasons',
    'What are personal benefits of  using social networking sites?': 'perceived_social_media_benefits',
    'When do you access social media websites?': 'times_using_social_media',
    'When you use social media did you forget about time?': 'forget_time_using_social_media',
    'Do you consider yourself addicted to social media?': 'subjective_social_media_addiction'
})

df3_clean

,age,gender,occupation,daily_occupation_hours,social_media_platforms,daily_social_media_hours,daily_family_hours,social_media_use_reasons,perceived_social_media_benefits,times_using_social_media,forget_time_using_social_media,subjective_social_media_addiction
0,22,male,student,6-8,"facebook, youtube, instagram, imo, telegram, w...",6+,1-2,"keep up with news/gossip/ trends, contact and ...","help with studies, staying connected with peop...","during my free time, during meal times",yes,yes
1,23,male,student,6-8,"facebook, youtube, imo, telegram, whatsapp, li...",4-5,1-2,"keep up with news/gossip/ trends, contact and ...","staying connected with people, learn new skills","during my free time, during meal times, any sp...",sometimes,no
2,24,male,student,2-4,"facebook, youtube, instagram, telegram, whatsapp",4-5,1-2,"keep up with news/gossip/ trends, contact and ...",staying connected with people,during my free time,yes,yes
3,23,male,student,8+,"facebook, youtube",4-5,4-5,"keep up with news/gossip/ trends, contact and ...","help with studies, entertainment","during my free time, any spare time",no,yes
4,20,male,student,6-8,"facebook, youtube, telegram, whatsapp",1-2,6+,"keep up with news/gossip/ trends, contact and ...","keep up with news/gossip/ trends, contact and ...","during my free time, during meal times",no,no
...,...,...,...,...,...,...,...,...,...,...,...,...
517,20,female,student,0-2,facebook,3-4,1-2,contact and connect with friends/ family,staying connected with people,while at school/university/work,no,no
518,21,female,student,6-8,"facebook, youtube, instagram, whatsapp",1-2,1-2,"keep up with news/gossip/ trends, contact and ...","help with studies, staying connected with peop...","during my free time, while at school/universit...",sometimes,no
519,22,male,student,2-4,"facebook, youtube, telegram, whatsapp",3-4,6+,"keep up with news/gossip/ trends, contact and ...","help with studies, staying connected with peop...","during my free time, during meal times, any sp...",sometimes,not sure
520,21,female,student,4-6,"facebook, youtube, instagram, telegram, whatsapp",1-2,1-2,"keep up with news/gossip/ trends, contact and ...",help with studies,during my free time,sometimes,no
521,22,male,student,2-4,"facebook, youtube, instagram, telegram, whatsapp",3-4,3-4,"keep up with news/gossip/ trends, contact and ...","help with studies, staying connected with peop...","during my free time, during social occasions",no,no

In [ ]:
# Set age range
df3_clean["age"] = pd.to_numeric(df3_clean["age"], errors="coerce")

df3_clean = df3_clean[(df3_clean["age"] >= 18) & (df3_clean["age"] <= 30)].copy()

df3_clean

,age,gender,occupation,daily_occupation_hours,social_media_platforms,daily_social_media_hours,daily_family_hours,social_media_use_reasons,perceived_social_media_benefits,times_using_social_media,forget_time_using_social_media,subjective_social_media_addiction
0,22,male,student,6-8,"facebook, youtube, instagram, imo, telegram, w...",6+,1-2,"keep up with news/gossip/ trends, contact and ...","help with studies, staying connected with peop...","during my free time, during meal times",yes,yes
1,23,male,student,6-8,"facebook, youtube, imo, telegram, whatsapp, li...",4-5,1-2,"keep up with news/gossip/ trends, contact and ...","staying connected with people, learn new skills","during my free time, during meal times, any sp...",sometimes,no
2,24,male,student,2-4,"facebook, youtube, instagram, telegram, whatsapp",4-5,1-2,"keep up with news/gossip/ trends, contact and ...",staying connected with people,during my free time,yes,yes
3,23,male,student,8+,"facebook, youtube",4-5,4-5,"keep up with news/gossip/ trends, contact and ...","help with studies, entertainment","during my free time, any spare time",no,yes
4,20,male,student,6-8,"facebook, youtube, telegram, whatsapp",1-2,6+,"keep up with news/gossip/ trends, contact and ...","keep up with news/gossip/ trends, contact and ...","during my free time, during meal times",no,no
...,...,...,...,...,...,...,...,...,...,...,...,...
517,20,female,student,0-2,facebook,3-4,1-2,contact and connect with friends/ family,staying connected with people,while at school/university/work,no,no
518,21,female,student,6-8,"facebook, youtube, instagram, whatsapp",1-2,1-2,"keep up with news/gossip/ trends, contact and ...","help with studies, staying connected with peop...","during my free time, while at school/universit...",sometimes,no
519,22,male,student,2-4,"facebook, youtube, telegram, whatsapp",3-4,6+,"keep up with news/gossip/ trends, contact and ...","help with studies, staying connected with peop...","during my free time, during meal times, any sp...",sometimes,not sure
520,21,female,student,4-6,"facebook, youtube, instagram, telegram, whatsapp",1-2,1-2,"keep up with news/gossip/ trends, contact and ...",help with studies,during my free time,sometimes,no
521,22,male,student,2-4,"facebook, youtube, instagram, telegram, whatsapp",3-4,3-4,"keep up with news/gossip/ trends, contact and ...","help with studies, staying connected with peop...","during my free time, during social occasions",no,no

# Combining DFs

In [46]:
df1_clean["source_dataset"] = "smmh.csv"
df2_clean["source_dataset"] = "Mental_Health_and_Social_Media_Balance_Dataset.csv"
df3_clean["source_dataset"] = "Social_Media_Impact_on_Daily_Lives.csv"

In [ ]:
# DF1: social media time ranges
df1_time_mapping = {
    "Less than an Hour": 0.5,
    "Between 1 and 2 hours": 1.5,
    "Between 2 and 3 hours": 2.5,
    "Between 3 and 4 hours": 3.5,
    "Between 4 and 5 hours": 4.5,
    "More than 5 hours": 5.5
}

# DF3: social media time ranges
df3_time_mapping = {
    "1-2": 1.5,
    "3-4": 3.5,
    "4-5": 4.5,
    "5-6": 5.5,
    "6+": 6
}

In [47]:
df1_combined = pd.DataFrame({
    "source_dataset": "smmh.csv",
    "age": df1_clean["age"],
    "gender": df1_clean["gender"].str.strip().str.lower(),
    "daily_digital_media_hours": df1_clean["daily_time_spent"].map(df1_time_mapping),
    "time_measure_type": "social_media_time",
    "platform_info": df1_clean["platforms_used"],
    "platform_count": df1_clean["platforms_used"].str.split(",").str.len(),
    "platform_info_type": "multiple_platforms"
})

df2_combined = pd.DataFrame({
    "source_dataset": "Mental_Health_and_Social_Media_Balance_Dataset.csv",
    "age": df2_clean["age"],
    "gender": df2_clean["gender"].str.strip().str.lower(),
    "daily_digital_media_hours": df2_clean["daily_screen_time_hours"],
    "time_measure_type": "screen_time",
    "platform_info": df2_clean["primary_social_media_platform"],
    "platform_count": 1,
    "platform_info_type": "primary_platform_only"
})

df3_combined = pd.DataFrame({
    "source_dataset": "Social_Media_Impact_on_Daily_Lives.csv",
    "age": df3_clean["age"],
    "gender": df3_clean["gender"].str.strip().str.lower(),
    "daily_digital_media_hours": df3_clean["daily_social_media_hours"].map(df3_time_mapping),
    "time_measure_type": "social_media_time",
    "platform_info": df3_clean["social_media_platforms"],
    "platform_count": df3_clean["social_media_platforms"].str.split(",").str.len(),
    "platform_info_type": "multiple_platforms"
})

In [50]:
combined_dfs = pd.concat(
    [df1_combined, df2_combined, df3_combined],
    ignore_index=True
)

combined_dfs.head()

,source_dataset,age,gender,daily_digital_media_hours,time_measure_type,platform_info,platform_count,platform_info_type
0,smmh.csv,21.0,male,2.5,social_media_time,"Facebook, Twitter, Instagram, YouTube, Discord...",6,multiple_platforms
1,smmh.csv,21.0,female,5.5,social_media_time,"Facebook, Twitter, Instagram, YouTube, Discord...",6,multiple_platforms
2,smmh.csv,21.0,female,3.5,social_media_time,"Facebook, Instagram, YouTube, Pinterest",4,multiple_platforms
3,smmh.csv,21.0,female,5.5,social_media_time,"Facebook, Instagram",2,multiple_platforms
4,smmh.csv,21.0,female,2.5,social_media_time,"Facebook, Instagram, YouTube",3,multiple_platforms

In [55]:
combined_dfs["source_dataset"].value_counts()

source_dataset
Social_Media_Impact_on_Daily_Lives.csv                446
smmh.csv                                              371
Mental_Health_and_Social_Media_Balance_Dataset.csv    171
Name: count, dtype: int64

## **Research Question & Exploratory Data Analysis**

## **Summary, Conclusions, and Recommendations**

## **References & Disclosures**